spring:
  cloud:
    gateway:
      routes:
        - id: ms-auth
          uri: lb://MS-AUTH
          predicates:
            - Path=/api/v1/auth/**

        - id: ms-questions
          uri: lb://MS-QUESTIONS
          predicates:
            - Path=/api/v1/questions/**

        - id: ms-test
          uri: lb://MS-TEST
          predicates:
            - Path=/api/v1/tests/**

        - id: ms-omr
          uri: lb://MS-OMR
          predicates:
            - Path=/process_image

        - id: ms-assess
          uri: lb://MS-ASSESS
          predicates:
            - Path=/api/v1/assessment/**
  application:
    name: MS-GATEWAY

eureka:
  client:
    service-url:
      defaultZone: http://ms-service-reg:8761/eureka/
