spring:
  cloud:
    gateway:
      routes:
        - id: ms-auth
          uri: lb://MS-AUTH
          predicates:
            - Path=/api/v1/auth/**

        - id: ms-questions
          uri: lb://MS-QUESTIONS
          predicates:
            - Path=/api/v1/questions/**

        - id: ms-tests
          uri: lb://MS-TEST
          predicates:
            - Path=/api/v1/tests/**
  application:
    name: MS-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/